bitbag_admin_ajax_attribute_by_code:
    path: /attribute-search-by-code
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_attribute:indexAction
        _format: json
        _sylius:
            permission: true
            repository:
                method: findByCodePart
                arguments:
                    - $code
                    - 25

bitbag_admin_ajax_attribute_by_id:
    path: /attribute-search-by-id
    methods: [GET]
    defaults:
        _controller: sylius.controller.product_attribute:indexAction
        _format: json
        _sylius:
            permission: true
            repository:
                method: findBy
                arguments: [id: $id]
